import * as db from '../db';

export const INITIAL_TOOLS = [
  // ── Lead Generation & CRM ──────────────────────────────────────
  {
    toolId: 'follow-up-boss',
    name: 'Follow Up Boss',
    tagline: 'The CRM built for real estate teams',
    description: 'CRM purpose-built for real estate with automatic lead routing, follow-up plans, and team accountability. The most widely used real estate CRM among high-producing teams.',
    websiteUrl: 'https://www.followupboss.com',
    affiliateUrl: 'https://www.followupboss.com?ref=agentos',
    category: 'lead_generation' as const,
    pricingModel: 'per_seat' as const,
    pricingFrom: 6900,
    pricingLabel: 'From $69/seat/mo',
    curationTier: 'vetted' as const,
    integrationStatus: 'none' as const,
    relevantLevels: [2, 3, 4, 5],
    tags: ['crm', 'lead routing', 'follow-up', 'team'],
    sortOrder: 1,
  },
  {
    toolId: 'kw-command',
    name: 'KW Command',
    tagline: "KW's all-in-one business platform",
    description: "Keller Williams' native business platform. Includes CRM, SmartPlans, market analytics, and the Command app ecosystem. Native to the KW ecosystem and included with KW membership.",
    websiteUrl: 'https://www.kwcommand.com',
    category: 'lead_generation' as const,
    pricingModel: 'free' as const,
    pricingLabel: 'Included with KW membership',
    curationTier: 'integrated' as const,
    integrationStatus: 'planned' as const,
    relevantLevels: [1, 2, 3, 4, 5, 6, 7],
    tags: ['crm', 'kw', 'command', 'smartplans'],
    sortOrder: 0,
  },
  {
    toolId: 'lofty',
    name: 'Lofty (formerly Chime)',
    tagline: 'AI-powered CRM with IDX website',
    description: 'Full-featured CRM with built-in AI lead scoring, IDX website, and automated follow-up. Strong option for teams wanting an all-in-one platform with a built-in website.',
    websiteUrl: 'https://www.lofty.com',
    affiliateUrl: 'https://www.lofty.com?ref=agentos',
    category: 'lead_generation' as const,
    pricingModel: 'paid' as const,
    pricingFrom: 40000,
    pricingLabel: 'From $400/mo',
    curationTier: 'vetted' as const,
    integrationStatus: 'none' as const,
    relevantLevels: [2, 3, 4, 5],
    tags: ['crm', 'idx', 'ai', 'lead scoring'],
    sortOrder: 2,
  },
  {
    toolId: 'kvcore',
    name: 'kvCORE',
    tagline: 'All-in-one real estate platform',
    description: 'Complete real estate platform with CRM, IDX website, lead generation, and marketing automation. Popular with brokerages for its team management features.',
    websiteUrl: 'https://www.insiderealestate.com',
    affiliateUrl: 'https://www.insiderealestate.com?ref=agentos',
    category: 'lead_generation' as const,
    pricingModel: 'per_seat' as const,
    pricingFrom: 50000,
    pricingLabel: 'From $500/mo',
    curationTier: 'listed' as const,
    integrationStatus: 'none' as const,
    relevantLevels: [3, 4, 5, 6, 7],
    tags: ['crm', 'idx', 'lead generation', 'brokerage'],
    sortOrder: 3,
  },

  // ── AI Writing & Compliance ────────────────────────────────────
  {
    toolId: 'chatgpt',
    name: 'ChatGPT',
    tagline: 'General-purpose AI writing assistant',
    description: "OpenAI's ChatGPT is the most versatile AI writing tool available. Useful for drafting listing descriptions, emails, scripts, and SOPs. Always run real estate content through AgentOS's compliance screener before using.",
    websiteUrl: 'https://chat.openai.com',
    affiliateUrl: 'https://openai.com/chatgpt?ref=agentos',
    category: 'ai_writing' as const,
    pricingModel: 'freemium' as const,
    pricingFrom: 2000,
    pricingLabel: 'Free · Plus $20/mo',
    curationTier: 'vetted' as const,
    integrationStatus: 'none' as const,
    relevantLevels: [1, 2, 3, 4, 5, 6, 7],
    endorsementQuote: "I use ChatGPT daily for first drafts. The key is always running the output through AgentOS's compliance screener before anything goes to a client.",
    endorsementContext: 'Used in ASRE implementation work',
    tags: ['ai writing', 'content', 'email', 'listing descriptions'],
    sortOrder: 1,
  },
  {
    toolId: 'claude',
    name: 'Claude (Anthropic)',
    tagline: 'The AI powering AgentOS — available directly',
    description: "Claude is the AI model powering AgentOS's coaching, compliance screening, and content generation. Access it directly at claude.ai for longer-form content, document analysis, and complex business planning tasks.",
    websiteUrl: 'https://claude.ai',
    affiliateUrl: 'https://claude.ai?ref=agentos',
    category: 'ai_writing' as const,
    pricingModel: 'freemium' as const,
    pricingFrom: 2000,
    pricingLabel: 'Free · Pro $20/mo',
    curationTier: 'vetted' as const,
    integrationStatus: 'native' as const,
    relevantLevels: [1, 2, 3, 4, 5, 6, 7],
    endorsementQuote: "Claude is the engine inside AgentOS. For complex tasks like business planning, SOP writing, or analyzing your market — it's exceptional.",
    tags: ['ai writing', 'business planning', 'document analysis'],
    sortOrder: 0,
  },
  {
    toolId: 'jasper',
    name: 'Jasper',
    tagline: 'AI writing for marketing teams',
    description: 'Marketing-focused AI writing platform with templates for social posts, email campaigns, listing descriptions, and blog content. Strong brand voice consistency features for teams.',
    websiteUrl: 'https://www.jasper.ai',
    affiliateUrl: 'https://www.jasper.ai?ref=agentos',
    category: 'ai_writing' as const,
    pricingModel: 'paid' as const,
    pricingFrom: 3900,
    pricingLabel: 'From $39/mo',
    curationTier: 'listed' as const,
    integrationStatus: 'none' as const,
    relevantLevels: [3, 4, 5, 6],
    tags: ['ai writing', 'marketing', 'social media', 'brand voice'],
    sortOrder: 3,
  },

  // ── Video & Presentations ─────────────────────────────────────
  {
    toolId: 'bombbomb',
    name: 'BombBomb',
    tagline: 'Video email for real estate professionals',
    description: 'Send personalized video messages instead of plain emails. Dramatically improves response rates for new lead outreach, client updates, and referral requests. Built specifically for real estate.',
    websiteUrl: 'https://www.bombbomb.com',
    affiliateUrl: 'https://www.bombbomb.com?ref=agentos',
    category: 'video_presentations' as const,
    pricingModel: 'paid' as const,
    pricingFrom: 3300,
    pricingLabel: 'From $33/mo',
    curationTier: 'vetted' as const,
    integrationStatus: 'planned' as const,
    relevantLevels: [1, 2, 3, 4, 5],
    endorsementQuote: 'A 60-second personal video beats a hundred cold emails. BombBomb is the tool that makes video outreach scalable.',
    tags: ['video email', 'lead response', 'client communication'],
    sortOrder: 1,
  },
  {
    toolId: 'loom',
    name: 'Loom',
    tagline: 'Async video messaging for teams',
    description: 'Record and share video messages instantly. Ideal for team training, SOP documentation, client walkthrough videos, and async communication with transaction coordinators.',
    websiteUrl: 'https://www.loom.com',
    affiliateUrl: 'https://www.loom.com?ref=agentos',
    category: 'video_presentations' as const,
    pricingModel: 'freemium' as const,
    pricingFrom: 1250,
    pricingLabel: 'Free · Business $12.50/mo',
    curationTier: 'vetted' as const,
    integrationStatus: 'none' as const,
    relevantLevels: [2, 3, 4, 5, 6, 7],
    tags: ['video', 'team training', 'async communication', 'sop'],
    sortOrder: 2,
  },
  {
    toolId: 'matterport',
    name: 'Matterport',
    tagline: '3D virtual tours for listings',
    description: 'Create immersive 3D virtual tours of properties. Buyers can walk through listings remotely. Proven to increase listing engagement and reduce days on market.',
    websiteUrl: 'https://matterport.com',
    affiliateUrl: 'https://matterport.com?ref=agentos',
    category: 'video_presentations' as const,
    pricingModel: 'freemium' as const,
    pricingFrom: 1100,
    pricingLabel: 'Free · Pro $11/mo',
    curationTier: 'listed' as const,
    integrationStatus: 'none' as const,
    relevantLevels: [1, 2, 3, 4],
    tags: ['virtual tours', '3d', 'listing marketing', 'photography'],
    sortOrder: 3,
  },

  // ── Transaction Management ─────────────────────────────────────
  {
    toolId: 'dotloop',
    name: 'Dotloop',
    tagline: 'Transaction management for real estate',
    description: 'Industry-leading transaction management platform. Create loops, collect signatures, and manage the entire contract-to-close workflow. Required or preferred at many KW Market Centers.',
    websiteUrl: 'https://www.dotloop.com',
    affiliateUrl: 'https://www.dotloop.com?ref=agentos',
    category: 'transaction_management' as const,
    pricingModel: 'paid' as const,
    pricingFrom: 3100,
    pricingLabel: 'From $31/mo',
    curationTier: 'vetted' as const,
    integrationStatus: 'planned' as const,
    relevantLevels: [1, 2, 3, 4, 5, 6, 7],
    endorsementQuote: 'Dotloop is the transaction backbone for most KW offices. Getting your TC proficient in Dotloop is one of the first hires that pays for itself.',
    tags: ['transaction management', 'esignature', 'contract', 'closing'],
    sortOrder: 1,
  },
  {
    toolId: 'docusign',
    name: 'DocuSign',
    tagline: 'eSignature and contract management',
    description: 'The global standard for electronic signatures. Essential for offers, listing agreements, and disclosure packages.',
    websiteUrl: 'https://www.docusign.com',
    affiliateUrl: 'https://www.docusign.com?ref=agentos',
    category: 'transaction_management' as const,
    pricingModel: 'paid' as const,
    pricingFrom: 1500,
    pricingLabel: 'From $15/mo',
    curationTier: 'vetted' as const,
    integrationStatus: 'planned' as const,
    relevantLevels: [1, 2, 3, 4],
    tags: ['esignature', 'contracts', 'documents'],
    sortOrder: 2,
  },
  {
    toolId: 'skyslope',
    name: 'SkySlope',
    tagline: 'Transaction management and compliance',
    description: 'Transaction management with built-in compliance review. Brokerages use it to ensure every file is complete before closing. Strong audit trail features.',
    websiteUrl: 'https://www.skyslope.com',
    affiliateUrl: 'https://www.skyslope.com?ref=agentos',
    category: 'transaction_management' as const,
    pricingModel: 'paid' as const,
    pricingFrom: 2500,
    pricingLabel: 'From $25/mo',
    curationTier: 'listed' as const,
    integrationStatus: 'none' as const,
    relevantLevels: [2, 3, 4, 5],
    tags: ['transaction management', 'compliance', 'audit'],
    sortOrder: 3,
  },

  // ── Financial & Business Intelligence ─────────────────────────
  {
    toolId: 'quickbooks-self-employed',
    name: 'QuickBooks Self-Employed',
    tagline: 'Accounting built for solo agents',
    description: "Tracks income, expenses, and mileage automatically. Generates Schedule C reports for tax prep. The most practical accounting solution for solo agents and small teams.",
    websiteUrl: 'https://quickbooks.intuit.com/self-employed',
    affiliateUrl: 'https://quickbooks.intuit.com/self-employed?ref=agentos',
    category: 'financial_intelligence' as const,
    pricingModel: 'paid' as const,
    pricingFrom: 1500,
    pricingLabel: 'From $15/mo',
    curationTier: 'vetted' as const,
    integrationStatus: 'planned' as const,
    relevantLevels: [1, 2, 3],
    tags: ['accounting', 'taxes', 'expense tracking', 'mileage'],
    sortOrder: 1,
  },
  {
    toolId: 'sequence-financial',
    name: 'Sequence',
    tagline: 'Smart banking for self-employed professionals',
    description: "Business banking designed for self-employed professionals. Automates Profit First allocation, tax withholding, and financial organization.",
    websiteUrl: 'https://www.sequence.com',
    affiliateUrl: 'https://www.sequence.com?ref=agentos',
    category: 'financial_intelligence' as const,
    pricingModel: 'freemium' as const,
    pricingLabel: 'Free · Pro available',
    curationTier: 'vetted' as const,
    integrationStatus: 'none' as const,
    relevantLevels: [1, 2, 3, 4],
    endorsementQuote: 'Sequence makes Profit First automatic. I recommend it to every agent who is serious about building real financial margin.',
    endorsementContext: 'Recommended in KW coaching sessions',
    tags: ['banking', 'profit first', 'financial automation'],
    sortOrder: 2,
  },
  {
    toolId: 'relay-banking',
    name: 'Relay',
    tagline: 'Business banking with Profit First built in',
    description: 'Free business banking with up to 20 checking accounts. Perfect for implementing Profit First methodology with separate accounts for income, profit, taxes, and operating expenses.',
    websiteUrl: 'https://www.relayfi.com',
    affiliateUrl: 'https://www.relayfi.com?ref=agentos',
    category: 'financial_intelligence' as const,
    pricingModel: 'free' as const,
    pricingLabel: 'Free',
    curationTier: 'listed' as const,
    integrationStatus: 'none' as const,
    relevantLevels: [1, 2, 3, 4],
    tags: ['banking', 'profit first', 'business accounts'],
    sortOrder: 3,
  },

  // ── Marketing & Social ────────────────────────────────────────
  {
    toolId: 'canva',
    name: 'Canva',
    tagline: 'Design tool for non-designers',
    description: 'The fastest way to create professional listing graphics, social media posts, email headers, and presentation decks. Real estate templates are built in.',
    websiteUrl: 'https://www.canva.com',
    affiliateUrl: 'https://www.canva.com?ref=agentos',
    category: 'marketing_social' as const,
    pricingModel: 'freemium' as const,
    pricingFrom: 1700,
    pricingLabel: 'Free · Pro $17/mo',
    curationTier: 'vetted' as const,
    integrationStatus: 'none' as const,
    relevantLevels: [1, 2, 3, 4],
    tags: ['design', 'social media', 'listing graphics', 'branding'],
    sortOrder: 1,
  },
  {
    toolId: 'homebot',
    name: 'Homebot',
    tagline: 'Automated home value reports for past clients',
    description: 'Sends monthly home value estimates to your past clients branded from you. Keeps you top-of-mind without manual effort. One of the highest-ROI retention tools in real estate.',
    websiteUrl: 'https://www.homebot.ai',
    affiliateUrl: 'https://www.homebot.ai?ref=agentos',
    category: 'marketing_social' as const,
    pricingModel: 'paid' as const,
    pricingFrom: 9900,
    pricingLabel: '$99/mo',
    curationTier: 'vetted' as const,
    integrationStatus: 'planned' as const,
    relevantLevels: [2, 3, 4, 5, 6, 7],
    endorsementQuote: 'Homebot is the single best ROI tool for staying top-of-mind with past clients.',
    tags: ['past clients', 'home values', 'referrals', 'retention'],
    sortOrder: 2,
  },
  {
    toolId: 'mailchimp',
    name: 'Mailchimp',
    tagline: 'Email marketing automation',
    description: 'Email marketing platform with automation, templates, and analytics. Build drip campaigns for new leads, past clients, and sphere of influence.',
    websiteUrl: 'https://mailchimp.com',
    affiliateUrl: 'https://mailchimp.com?ref=agentos',
    category: 'marketing_social' as const,
    pricingModel: 'freemium' as const,
    pricingFrom: 1300,
    pricingLabel: 'Free · Essentials $13/mo',
    curationTier: 'listed' as const,
    integrationStatus: 'none' as const,
    relevantLevels: [1, 2, 3, 4],
    tags: ['email marketing', 'automation', 'drip campaigns', 'newsletters'],
    sortOrder: 3,
  },
  {
    toolId: 'coffee-and-contracts',
    name: 'Coffee & Contracts',
    tagline: 'Done-for-you social media content',
    description: 'Monthly social media templates, captions, and content calendars designed specifically for real estate agents. Saves hours of content creation time.',
    websiteUrl: 'https://coffeeandcontracts.com',
    affiliateUrl: 'https://coffeeandcontracts.com?ref=agentos',
    category: 'marketing_social' as const,
    pricingModel: 'paid' as const,
    pricingFrom: 5400,
    pricingLabel: '$54/mo',
    curationTier: 'vetted' as const,
    integrationStatus: 'none' as const,
    relevantLevels: [1, 2, 3],
    tags: ['social media', 'content', 'templates', 'instagram'],
    sortOrder: 4,
  },

  // ── Learning & Coaching ───────────────────────────────────────
  {
    toolId: 'maps-coaching',
    name: 'MAPS Coaching',
    tagline: "Keller Williams' professional coaching program",
    description: "KW's official coaching program with 1:1 and group coaching options. The foundation the MREA framework is built on.",
    websiteUrl: 'https://www.mapscoaching.com',
    category: 'learning_coaching' as const,
    pricingModel: 'paid' as const,
    pricingFrom: 100000,
    pricingLabel: 'From $1,000/mo',
    curationTier: 'vetted' as const,
    integrationStatus: 'native' as const,
    relevantLevels: [1, 2, 3, 4, 5, 6, 7],
    endorsementQuote: 'MAPS Coaching and AgentOS are designed to work together. MAPS provides the coaching relationship; AgentOS provides the operating system.',
    tags: ['coaching', 'kw', 'mrea', 'business building'],
    sortOrder: 0,
  },
  {
    toolId: 'kw-university',
    name: 'KW University',
    tagline: 'KW training and education platform',
    description: 'Online learning platform with courses on scripts, lead generation, negotiation, and business building. Included with KW membership.',
    websiteUrl: 'https://www.kw.com',
    category: 'learning_coaching' as const,
    pricingModel: 'free' as const,
    pricingLabel: 'Included with KW membership',
    curationTier: 'integrated' as const,
    integrationStatus: 'none' as const,
    relevantLevels: [1, 2, 3, 4, 5],
    tags: ['education', 'kw', 'training', 'scripts'],
    sortOrder: 1,
  },

  // ── Compliance ────────────────────────────────────────────────
  {
    toolId: 'fair-housing-institute',
    name: 'Fair Housing Institute',
    tagline: 'Fair Housing training and certification',
    description: "Online Fair Housing training courses for agents and brokers. AgentOS's compliance screener handles day-to-day content screening; this handles the underlying knowledge and certification.",
    websiteUrl: 'https://www.fairhousinginstitute.com',
    affiliateUrl: 'https://www.fairhousinginstitute.com?ref=agentos',
    category: 'compliance' as const,
    pricingModel: 'paid' as const,
    pricingFrom: 2500,
    pricingLabel: 'From $25/course',
    curationTier: 'vetted' as const,
    integrationStatus: 'none' as const,
    relevantLevels: [1, 2, 3, 4, 5, 6, 7],
    tags: ['fair housing', 'compliance', 'continuing education', 'certification'],
    sortOrder: 1,
  },

  // ── Team & Operations ─────────────────────────────────────────
  {
    toolId: 'slack',
    name: 'Slack',
    tagline: 'Team communication and coordination',
    description: 'Channels-based team communication. Essential once you have more than 2 people on the team.',
    websiteUrl: 'https://slack.com',
    affiliateUrl: 'https://slack.com?ref=agentos',
    category: 'team_operations' as const,
    pricingModel: 'freemium' as const,
    pricingFrom: 750,
    pricingLabel: 'Free · Pro $7.50/seat/mo',
    curationTier: 'vetted' as const,
    integrationStatus: 'none' as const,
    relevantLevels: [3, 4, 5, 6, 7],
    tags: ['team communication', 'channels', 'operations'],
    sortOrder: 1,
  },
  {
    toolId: 'calendly',
    name: 'Calendly',
    tagline: 'Automated scheduling for agents',
    description: 'Eliminate the back-and-forth of scheduling buyer consultations, listing appointments, and coaching sessions. Integrates with Google Calendar.',
    websiteUrl: 'https://calendly.com',
    affiliateUrl: 'https://calendly.com?ref=agentos',
    category: 'team_operations' as const,
    pricingModel: 'freemium' as const,
    pricingFrom: 1000,
    pricingLabel: 'Free · Teams $10/seat/mo',
    curationTier: 'vetted' as const,
    integrationStatus: 'planned' as const,
    relevantLevels: [1, 2, 3, 4, 5],
    tags: ['scheduling', 'appointments', 'calendar', 'automation'],
    sortOrder: 2,
  },
  {
    toolId: 'notion',
    name: 'Notion',
    tagline: 'All-in-one workspace for teams',
    description: 'Flexible workspace for SOPs, meeting notes, project management, and team wikis. Great for documenting processes as your team grows.',
    websiteUrl: 'https://www.notion.so',
    affiliateUrl: 'https://www.notion.so?ref=agentos',
    category: 'team_operations' as const,
    pricingModel: 'freemium' as const,
    pricingFrom: 1000,
    pricingLabel: 'Free · Plus $10/seat/mo',
    curationTier: 'listed' as const,
    integrationStatus: 'none' as const,
    relevantLevels: [2, 3, 4, 5, 6, 7],
    tags: ['workspace', 'sop', 'wiki', 'project management'],
    sortOrder: 3,
  },

  // ── Data & Analytics ──────────────────────────────────────────
  {
    toolId: 'realtors-mls',
    name: 'MLS / Realtor.com',
    tagline: 'Market data and listing syndication',
    description: 'Your local MLS is the foundation of market data. Realtor.com syndicates your listings nationally. Understanding how to pull CMAs, market stats, and listing analytics is essential.',
    websiteUrl: 'https://www.realtor.com',
    category: 'data_analytics' as const,
    pricingModel: 'paid' as const,
    pricingLabel: 'Included with MLS dues',
    curationTier: 'integrated' as const,
    integrationStatus: 'none' as const,
    relevantLevels: [1, 2, 3, 4, 5, 6, 7],
    tags: ['mls', 'market data', 'listings', 'cma'],
    sortOrder: 0,
  },
  {
    toolId: 'altos-research',
    name: 'Altos Research',
    tagline: 'Real-time market analytics',
    description: 'Real-time market statistics and trends. Use data to position yourself as the market expert in your area. Great for content creation and client consultations.',
    websiteUrl: 'https://www.altosresearch.com',
    affiliateUrl: 'https://www.altosresearch.com?ref=agentos',
    category: 'data_analytics' as const,
    pricingModel: 'paid' as const,
    pricingFrom: 5000,
    pricingLabel: 'From $50/mo',
    curationTier: 'vetted' as const,
    integrationStatus: 'none' as const,
    relevantLevels: [2, 3, 4, 5, 6, 7],
    endorsementQuote: 'Altos Research gives you the data to be the smartest person in the room on market conditions. Use it in every listing presentation.',
    tags: ['market analytics', 'data', 'trends', 'market reports'],
    sortOrder: 1,
  },
];

export async function seedTools() {
  console.log('[Seed] Starting AI Tools directory seed...');
  let seeded = 0;

  for (const tool of INITIAL_TOOLS) {
    try {
      await db.upsertTool({
        ...tool,
        isApproved: true,
        relevantLevels: tool.relevantLevels,
        tags: tool.tags,
      } as any);
      seeded++;
    } catch (e: any) {
      console.error(`[Seed] Failed to seed tool ${tool.toolId}:`, e.message);
    }
  }

  console.log(`[Seed] AI Tools seed complete — ${seeded} tools added`);
}
